/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mapd_CiderJNI */

#ifndef _Included_com_mapd_CiderJNI
#define _Included_com_mapd_CiderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mapd_CiderJNI
 * Method:    processBlocks
 * Signature: (JLjava/lang/String;Ljava/lang/String;[J[J[J[JI)I
 */
JNIEXPORT jint JNICALL Java_com_mapd_CiderJNI_processBlocks
  (JNIEnv *, jclass, jlong, jstring, jstring, jlongArray, jlongArray, jlongArray, jlongArray, jint);

/*
 * Class:     com_mapd_CiderJNI
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mapd_CiderJNI_init
  (JNIEnv *, jclass);

/*
 * Class:     com_mapd_CiderJNI
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mapd_CiderJNI_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
